### ISSUE TITLE
DAG import error

### ISSUE THREAD

**Issue by sokui** [blockchain-etl/ethereum-etl-airflow#571]
HI,

I am trying to set up the google composer environment for this repo. I follow the instruction, using the image version `--image-version=composer-2.1.14-airflow-2.5.1`. Composer environment was successfully created in cloud. However, there are error messages complaining about the DAG import showing in the airflow web UI. These error messages only show the last two lines of the stack trace. So I cannot locate where the error happens in the real code. Could you pls help? Totally 5 DAGs cannot be imported.

The error message shows:

```
Broken DAG: [/home/airflow/gcs/dags/ethereum_verify_streaming_dag.py] Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/composer/custom_log_filter.py", line 27, in _is_redis_warning
    return record.getMessage().startswith('You have configured a result_backend of redis://')
  File "/opt/python3.8/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

```
Broken DAG: [/home/airflow/gcs/dags/ethereum_export_dag.py] Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/composer/custom_log_filter.py", line 27, in _is_redis_warning
    return record.getMessage().startswith('You have configured a result_backend of redis://')
  File "/opt/python3.8/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

```
Broken DAG: [/home/airflow/gcs/dags/ethereum_amend_dag.py] Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/composer/custom_log_filter.py", line 27, in _is_redis_warning
    return record.getMessage().startswith('You have configured a result_backend of redis://')
  File "/opt/python3.8/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

```
Broken DAG: [/home/airflow/gcs/dags/ethereum_load_dag.py] Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/composer/custom_log_filter.py", line 27, in _is_redis_warning
    return record.getMessage().startswith('You have configured a result_backend of redis://')
  File "/opt/python3.8/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

```
Broken DAG: [/home/airflow/gcs/dags/ethereum_parse_dag.py] Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/composer/custom_log_filter.py", line 27, in _is_redis_warning
    return record.getMessage().startswith('You have configured a result_backend of redis://')
  File "/opt/python3.8/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

**Comment by sokui** [comment]
nvm. found the issue
